# 1 Read the dataset, show its head, shape and description

In [77]:
import pandas as pd

data = pd.read_csv("./AirQualityUCI.csv", sep=";")

display(data.head())
print(data.shape)
display(data.describe())

,Date,Time,X00,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12,X13,X14,X15
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN,NaN
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN,NaN
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN,NaN
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN,NaN
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN,NaN

(9471, 18)

,X00,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12,X13,X14,X15
count,7765.000000,8991.000000,914.000000,9357.000000,8991.000000,7718.000000,8991.000000,7715.000000,8991.000000,8991.000000,8991.000000,8991.000000,8991.000000,0.0,0.0,0.0
mean,2.127521,1099.833166,218.811816,9.688704,939.153376,246.896735,835.493605,113.091251,1456.264598,1022.906128,18.317829,49.234201,1.025530,NaN,NaN,NaN
std,1.463171,217.080037,204.459921,7.559785,266.831429,212.979168,256.817320,48.370108,346.206794,398.484288,8.832116,17.316892,0.403813,NaN,NaN,NaN
min,0.000000,647.000000,7.000000,0.000000,383.000000,2.000000,322.000000,2.000000,551.000000,221.000000,-1.900000,9.200000,0.184700,NaN,NaN,NaN
25%,1.000000,937.000000,67.000000,4.000000,734.500000,98.000000,658.000000,78.000000,1227.000000,731.500000,11.800000,35.800000,0.736800,NaN,NaN,NaN
50%,1.800000,1063.000000,150.000000,7.900000,909.000000,180.000000,806.000000,109.000000,1463.000000,963.000000,17.800000,49.600000,0.995400,NaN,NaN,NaN
75%,2.900000,1231.000000,297.000000,13.600000,1116.000000,326.000000,969.500000,142.000000,1674.000000,1273.500000,24.400000,62.500000,1.313700,NaN,NaN,NaN
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,NaN,NaN,NaN

# 2 Eliminate totally null columns and totally null rows, eliminate columnswith less than 1/3 of non null values; fill the remainingNaNvalues withthe mean of the column

In [78]:
data.dropna(axis=0, how="all", inplace=True) # rows totally null
data.dropna(axis=1, how="all", inplace=True) # cols totally null
data.dropna(axis=1, thresh=1/3*data.shape[0], inplace=True) # cols totally null
for c in data.columns[2:]:
    new_col = data[c].copy()
    mean = data[c].mean()
    for i in range(len(new_col)):
        if pd.isna(new_col[i]) : 
            new_col[i] = mean
    data[c] = new_col
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9357 entries, 0 to 9356
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    9357 non-null   object
 1   Time    9357 non-null   object
 2   X00     9357 non-null   float64
 3   X01     9357 non-null   float64
 4   X03     9357 non-null   float64
 5   X04     9357 non-null   float64
 6   X05     9357 non-null   float64
 7   X06     9357 non-null   float64
 8   X07     9357 non-null   float64
 9   X08     9357 non-null   float64
 10  X09     9357 non-null   float64
 11  X10     9357 non-null   float64
 12  X11     9357 non-null   float64
 13  X12     9357 non-null   float64
dtypes: float64(12), object(2)
memory usage: 1.3+ MB

# 3 DropTime, convertDatefromstringtodatetimeand group by Dateusing mean as aggregate function

In [79]:
data['Datetime'] = pd.to_datetime(data['Date'] + ' ' + data['Time'], format='%d/%m/%Y %H.%M.%S')
data.drop(columns=["Date","Time"], inplace=True)
data_grouped = data.groupby(by="Datetime").mean()
data_grouped

,X00,X01,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12
Datetime,,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
2004-03-10 19:00:00,2.0,1292.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2004-03-10 20:00:00,2.2,1402.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
2004-03-10 21:00:00,2.2,1376.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
2004-03-10 22:00:00,1.6,1272.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...
2005-04-04 10:00:00,3.1,1314.0,13.5,1101.0,472.0,539.0,190.0,1374.0,1729.0,21.9,29.3,0.7568
2005-04-04 11:00:00,2.4,1163.0,11.4,1027.0,353.0,604.0,179.0,1264.0,1269.0,24.3,23.7,0.7119
2005-04-04 12:00:00,2.4,1142.0,12.4,1063.0,293.0,603.0,175.0,1241.0,1092.0,26.9,18.3,0.6406
2005-04-04 13:00:00,2.1,1003.0,9.5,961.0,235.0,702.0,156.0,1041.0,770.0,28.3,13.5,0.5139
2005-04-04 14:00:00,2.2,1071.0,11.9,1047.0,265.0,654.0,168.0,1129.0,816.0,28.5,13.1,0.5028

# 4
- Discretise continuous values with two bins,kmeans strategy and onehot-dense encoding
- Discretization/encoding generates 0/1 values; convert the binary values obtained into boolean, as requested byApriori

In [80]:
from sklearn.preprocessing import KBinsDiscretizer
discretizer = KBinsDiscretizer(n_bins=2, encode="onehot-dense", strategy="kmeans")
df = pd.DataFrame(
    discretizer.fit_transform(data_grouped),
    columns=discretizer.get_feature_names_out()
)
df = df.astype(bool)

/usr/local/lib/python3.11/site-packages/sklearn/preprocessing/_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(

# 5) et the names of two columns generated by the discretisation of eachattributeAtoA_low,A_high(with discretisation/one-hot-encoding,each original column generates two columns, the first is for thelowval-ues, the second for thehighvalues)

In [81]:
def rename_col(col:str):
    parts = col.split("_")
    if parts[1] == "0.0" : return f"{parts[0]}_low"
    else : return f"{parts[0]}_high"
    
df = df.rename(columns=rename_col)
df

,X00_low,X00_high,X01_low,X01_high,X03_low,X03_high,X04_low,X04_high,X05_low,X05_high,...,X08_low,X08_high,X09_low,X09_high,X10_low,X10_high,X11_low,X11_high,X12_low,X12_high
0,True,False,False,True,True,False,False,True,True,False,...,False,True,False,True,True,False,False,True,True,False
1,True,False,False,True,True,False,True,False,True,False,...,False,True,True,False,True,False,True,False,True,False
2,True,False,False,True,True,False,True,False,True,False,...,False,True,True,False,True,False,False,True,True,False
3,True,False,False,True,True,False,True,False,True,False,...,False,True,False,True,True,False,False,True,True,False
4,True,False,False,True,True,False,True,False,True,False,...,False,True,True,False,True,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9352,False,True,False,True,False,True,False,True,False,True,...,True,False,False,True,False,True,True,False,True,False
9353,True,False,True,False,True,False,False,True,True,False,...,True,False,False,True,False,True,True,False,True,False
9354,True,False,True,False,True,False,False,True,True,False,...,True,False,True,False,False,True,True,False,True,False
9355,True,False,True,False,True,False,True,False,True,False,...,True,False,True,False,False,True,True,False,True,False
9356,True,False,True,False,True,False,False,True,True,False,...,True,False,True,False,False,True,True,False,True,False

# 6 find a value ofmin_supportsuch that the Apriori algorithm generatesat least 8 frequent itemsets with at least 2 items, output the result

In [82]:
from mlxtend.frequent_patterns import apriori, association_rules
import numpy as np
min_supports = np.arange(1, 0, -0.0001)
for min_support in min_supports:
    frequent_itemsets = apriori(df, min_support=min_support, use_colnames=True)
    
    frequent_itemsets_with_at_least_2 = frequent_itemsets[frequent_itemsets['itemsets'].apply(len) >= 2]
    
    if len(frequent_itemsets_with_at_least_2) >= 8:
        print(f"With min_support={min_support:.2f}, we have {len(frequent_itemsets_with_at_least_2)} frequent itemsets with at least 2 items.")
        break

With min_support=0.66, we have 8 frequent itemsets with at least 2 items.

# 7 find the minimum metric threshold such that at least 100 associationrules are extracted from the frequent itemsets found and show the met-rics used and the best 10 rules by descending confidence and support

In [83]:
min_thresholds = np.arange(0.01, 0, -0.0001)
for min_threshold in min_thresholds:
    rules = association_rules(frequent_itemsets, min_threshold=min_threshold)
    
    if len(rules) >= 100:
        print(f"With min_threshold={min_threshold:.4f}, we have {len(rules)} rules.")
        
        rules = rules.sort_values(by=['confidence', 'support'], ascending=[False, False])
        print("Top 10 rules:")
        print(rules.head(10))
        break